### ISSUE TITLE
where is `ensure` ?

### ISSUE THREAD

**Issue by funny-falcon** [emcien/iso_latte#2]
https://github.com/emcien/iso_latte/blob/master/lib/iso_latte.rb#L87

**Comment by nevinera** [comment]
I guess the comment was too strong? I meant that the `finish` hook executes after the subprocess terminates, regardless of its termination state. An `ensure` would mean that if you raised an exception from your `fault` hook (for example), the `finish` hook would still execute.

I can see how the comment might imply that, but it would be unexpected behavior otherwise - I'll change the comment.

**Comment by nevinera** [comment]
I don't actually see a strong reason to handle it one way or the other - if you have a good argument that the `finish` callback should execute even if one of the others raises, I'll consider changing that.

**Comment by nevinera** [comment]
Did not mean to reopen >.<
